### ISSUE TITLE
[Solved with firmware update to 3.5.8_1096] - Issue on migration or new version

### ISSUE THREAD

**Issue by lordvault** [Concentricc/xiaomi_vacuum#15]
Hi, 

I recently had to move all my configuration to a new microSD cuz an error on my las raspberry config. When i restored the bakcup and set the environment i detect this issue and the system dont add the vacuum to the devices on the hass. 

My configuration: 

```
#Hacs xiaomi vacumm
vacuum:
  - platform: xiaomi_vacuum
    host: 192.168.0.1XX
    token: "the token info"
    name: Robotina
```

## System Health

version | 2021.1.5
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.83-v7+
arch | armv7l
timezone | America/Bogota

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4901
Installed Version | 1.10.1
Stage | running
Available Repositories | 710
Installed Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Raspbian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | 2021.01.7
docker_version | 20.10.2
disk_total | 14.0 GB
disk_used | 5.3 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.2.0), Bitwarden RS (0.7.0), Duck DNS (1.12.4), NGINX Home Assistant SSL proxy (3.0.1), Nginx Proxy Manager (0.8.2), MariaDB (2.2.1), SQLite Web (2.3.2), Home Assistant Google Drive Backup (0.103.1), MQTT Server & Web client (1.2.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
mode | storage
views | 8
resources | 3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

I attach the log errors. 

```
Logger: custom_components.xiaomi_vacuum.miio.device
Source: custom_components/xiaomi_vacuum/miio/device.py:218
Integration: Xiaomi Vacuum
First occurred: 10:38:07 AM (3 occurrences)
Last logged: 10:38:17 AM

Unable to request properties [{'did': 'battery', 'siid': 2, 'piid': 1}, {'did': 'state', 'siid': 2, 'piid': 2}, {'did': 'error', 'siid': 3, 'piid': 1}, {'did': 'status', 'siid': 3, 'piid': 2}, {'did': 'brush_left_time', 'siid': 26, 'piid': 1}, {'did': 'brush_life_level', 'siid': 26, 'piid': 2}, {'did': 'filter_life_level', 'siid': 27, 'piid': 1}, {'did': 'filter_left_time', 'siid': 27, 'piid': 2}, {'did': 'brush_left_time2', 'siid': 28, 'piid': 1}, {'did': 'brush_life_level2', 'siid': 28, 'piid': 2}, {'did': 'operating_mode', 'siid': 18, 'piid': 1}, {'did': 'area', 'siid': 18, 'piid': 3}, {'did': 'timer', 'siid': 18, 'piid': 2}, {'did': 'fan_speed', 'siid': 18, 'piid': 6}]
Unable to request properties [{'did': 'last_clean', 'siid': 18, 'piid': 13}, {'did': 'total_clean_count', 'siid': 18, 'piid': 14}, {'did': 'total_area', 'siid': 18, 'piid': 15}, {'did': 'total_log_start', 'siid': 18, 'piid': 16}, {'did': 'button_led', 'siid': 18, 'piid': 17}, {'did': 'clean_success', 'siid': 18, 'piid': 18}, {'did': 'life_sieve', 'siid': 19, 'piid': 1}, {'did': 'life_brush_side', 'siid': 19, 'piid': 2}, {'did': 'life_brush_main', 'siid': 19, 'piid': 3}, {'did': 'dnd_enabled', 'siid': 20, 'piid': 1}, {'did': 'dnd_start_time', 'siid': 20, 'piid': 2}, {'did': 'dnd_stop_time', 'siid': 20, 'piid': 3}, {'did': 'map_view', 'siid': 23, 'piid': 1}, {'did': 'audio_volume', 'siid': 24, 'piid': 1}]
Unable to request properties [{'did': 'audio_language', 'siid': 24, 'piid': 3}, {'did': 'timezone', 'siid': 25, 'piid': 1}]
```

```
Logger: homeassistant.components.vacuum
Source: custom_components/xiaomi_vacuum/miio/miot_device.py:64
Integration: Vacuum (documentation, issues)
First occurred: 10:38:17 AM (1 occurrences)
Last logged: 10:38:17 AM

xiaomi_vacuum: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_vacuum/vacuum.py", line 322, in update
    state = self._vacuum.status()
  File "/config/custom_components/xiaomi_vacuum/miio/dreamevacuum.py", line 260, in status
    return self.get_properties_for_dataclass(DreameStatus)
  File "/config/custom_components/xiaomi_vacuum/miio/miot_device.py", line 63, in get_properties_for_dataclass
    response = {
  File "/config/custom_components/xiaomi_vacuum/miio/miot_device.py", line 64, in <dictcomp>
    prop["did"]: prop["value"] if prop["code"] == 0 else None
TypeError: list indices must be integers or slices, not str
```

**Comment by Radlagerkok** [comment]
Has your vacuum updated to version 3.5.8_1096? could this be a problem? If I update the vacuum, won't there be any problems?

**Comment by lordvault** [comment]
> Has your vacuum updated to version 3.5.8_1096? could this be a problem? If I update the vacuum, won't there be any problems?

hi @Radlagerkok, at this moment the vacumm have 3.5.8_1059 😮 but the app says that i already have the latest version. 

![15](https://user-images.githubusercontent.com/6520372/106468623-2c745880-646c-11eb-9a6f-1380cbdee309.jpg)

**Comment by Radlagerkok** [comment]
![IMG_20210201_204437](https://user-images.githubusercontent.com/67847514/106496798-5bbbb180-64ce-11eb-87e9-cba0adc7bded.jpg)

**Comment by Radlagerkok** [comment]
At 3.5.8_1096, everything works in the home assistant.  In mi home, the map is divided into zones.
![Screenshot_2021-02-02-13-26-18-139_io homeassistant companion android](https://user-images.githubusercontent.com/67847514/106587705-fcf04980-655a-11eb-8ccd-28174e45f298.jpg)
![Screenshot_2021-02-02-13-30-54-061_com xiaomi smarthome](https://user-images.githubusercontent.com/67847514/106587708-fd88e000-655a-11eb-8b80-57d0cd94a158.jpg)

**Comment by lordvault** [comment]
I was looking on some reddit and forums and the new version is available for some users not for every-one, i think they are rolling to a small group of people and maibe on future they make the realease available for every one. I think the only solution is wait to have the new firmware version. 
Other solution its try to make a downgrade for the xiaomi_vacuum component maibe from an old bakcup and dont upgrade the version until the new firmware is avialable for me.

**Comment by Radlagerkok** [comment]
some people put the region of Singapore or Germany.  An update came to them.  You can also create another mihome account and link the robot there.  It will update.  My robot updated yesterday

**Comment by lordvault** [comment]
I finally receive the firmware update and i have back on the hass the vacumm, tnks @Radlagerkok for your help.!

**Comment by arisermpo87** [comment]
Hey! I'm having the same issue, even with the latest firmware.

**Comment by ionuttimofte53** [comment]
same here. i had the isue before and after the rooms update. here is the log: 

2021-02-10 11:07:04 INFO (MainThread) [custom_components.hacs]
-------------------------------------------------------------------
HACS (Home Assistant Community Store)
Version: 1.11.1
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2021-02-10 11:07:05 DEBUG (MainThread) [custom_components.hacs] Can update 263 repositories
2021-02-10 11:07:05 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.HACS_REPO
2021-02-10 11:07:05 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Checking repository.
2021-02-10 11:07:05 INFO (MainThread) [homeassistant.components.light] Setting up light.tradfri
2021-02-10 11:07:05 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.tradfri
2021-02-10 11:07:05 INFO (MainThread) [homeassistant.components.switch] Setting up switch.tradfri
2021-02-10 11:07:05 INFO (SyncWorker_0) [homeassistant.loader] Loaded cover from homeassistant.components.cover
2021-02-10 11:07:05 INFO (MainThread) [homeassistant.setup] Setting up cover
2021-02-10 11:07:05 INFO (MainThread) [homeassistant.setup] Setup of domain cover took 0.0 seconds
2021-02-10 11:07:05 INFO (MainThread) [homeassistant.components.tuya] Tuya discovery device poll interval set to 900 seconds
2021-02-10 11:07:05 INFO (MainThread) [homeassistant.components.tuya] Tuya query device poll interval set to 120 seconds
2021-02-10 11:07:05 INFO (MainThread) [homeassistant.components.cover] Setting up cover.tradfri
2021-02-10 11:07:05 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Running checks against 1.11.1
2021-02-10 11:07:05 INFO (MainThread) [homeassistant.components.switch] Setting up switch.tuya
2021-02-10 11:07:06 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> All (0) checks passed
2021-02-10 11:07:06 INFO (MainThread) [custom_components.hacs] <Integration hacs/integration> Registration completed
2021-02-10 11:07:06 INFO (MainThread) [custom_components.hacs] Restore started
2021-02-10 11:07:06 DEBUG (MainThread) [queueman.manager] Checking out tasks to execute
2021-02-10 11:07:06 DEBUG (MainThread) [queueman.manager] Starting queue execution for 744 tasks
2021-02-10 11:07:06 DEBUG (MainThread) [queueman.manager] Queue execution finished for 744 tasks finished in 0.36 seconds
2021-02-10 11:07:06 INFO (MainThread) [custom_components.hacs] Restore done
2021-02-10 11:07:06 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.SENSOR
2021-02-10 11:07:06 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.WAITING
2021-02-10 11:07:06 INFO (MainThread) [custom_components.hacs] Setup complete, waiting for Home Assistant before startup tasks starts
2021-02-10 11:07:06 INFO (MainThread) [custom_components.hacs] HACS is enabled
2021-02-10 11:07:06 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.hacs
2021-02-10 11:07:09 ERROR (SyncWorker_3) [custom_components.xiaomi_vacuum.miio.miioprotocol] Unable to discover a device at address 10.128.191.195
2021-02-10 11:07:09 ERROR (SyncWorker_3) [custom_components.xiaomi_vacuum.miio.device] Unable to request properties [{'did': 'battery', 'siid': 2, 'piid': 1}, {'did': 'state', 'siid': 2, 'piid': 2}, {'did': 'error', 'siid': 3, 'piid': 1}, {'did': 'status', 'siid': 3, 'piid': 2}, {'did': 'brush_left_time', 'siid': 26, 'piid': 1}, {'did': 'brush_life_level', 'siid': 26, 'piid': 2}, {'did': 'filter_life_level', 'siid': 27, 'piid': 1}, {'did': 'filter_left_time', 'siid': 27, 'piid': 2}, {'did': 'brush_left_time2', 'siid': 28, 'piid': 1}, {'did': 'brush_life_level2', 'siid': 28, 'piid': 2}, {'did': 'operating_mode', 'siid': 18, 'piid': 1}, {'did': 'area', 'siid': 18, 'piid': 3}, {'did': 'timer', 'siid': 18, 'piid': 2}, {'did': 'fan_speed', 'siid': 18, 'piid': 6}]
2021-02-10 11:07:11 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.STARTUP
2021-02-10 11:07:11 INFO (MainThread) [custom_components.hacs] setup task HacsSetupTask.CATEGORIES
2021-02-10 11:07:11 DEBUG (SyncWorker_7) [custom_components.hacs] Starting setup task: Extra stores
2021-02-10 11:07:11 DEBUG (SyncWorker_7) [custom_components.hacs] Enable category: HacsCategory.INTEGRATION
2021-02-10 11:07:11 DEBUG (SyncWorker_7) [custom_components.hacs] Enable category: HacsCategory.PLUGIN
2021-02-10 11:07:11 DEBUG (SyncWorker_7) [custom_components.hacs] Enable category: HacsCategory.THEME
2021-02-10 11:07:12 DEBUG (MainThread) [queueman.manager] The queue is empty
2021-02-10 11:07:12 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.critical'. Content did not change
2021-02-10 11:07:12 INFO (MainThread) [custom_components.hacs] Loading known repositories
2021-02-10 11:07:12 DEBUG (MainThread) [custom_components.hacs] Got 93 elements for HacsCategory.REMOVED
2021-02-10 11:07:12 DEBUG (MainThread) [custom_components.hacs] Can update 263 repositories, items in queue 3
2021-02-10 11:07:12 DEBUG (MainThread) [queueman.manager] Checking out tasks to execute
2021-02-10 11:07:12 DEBUG (MainThread) [queueman.manager] Starting queue execution for 3 tasks
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] Got 479 elements for HacsCategory.INTEGRATION
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] Got 62 elements for HacsCategory.THEME
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] Got 207 elements for HacsCategory.PLUGIN
2021-02-10 11:07:13 DEBUG (MainThread) [queueman.manager] Queue execution finished for 3 tasks finished in 0.48 seconds
2021-02-10 11:07:13 DEBUG (MainThread) [queueman.manager] 1 taks remaining in the queue
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] Starting recurring background task for installed repositories
2021-02-10 11:07:13 DEBUG (MainThread) [queueman.manager] Checking out tasks to execute
2021-02-10 11:07:13 DEBUG (MainThread) [queueman.manager] Starting queue execution for 15 tasks
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] <Integration lukas-hetzenecker/home-assistant-remote> Checking repository.
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Getting repository information
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] <Plugin iantrich/config-template-card> Getting repository information
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] <Integration bruxy70/Garbage-Collection> Getting repository information
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] <Plugin maykar/lovelace-swipe-navigation> Getting repository information
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-slider-entity-row> Getting repository information
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] <Plugin amaximus/garbage-collection-card> Getting repository information
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] <Plugin bramkragten/weather-card> Getting repository information
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] <Plugin kalkih/mini-graph-card> Getting repository information
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] <Plugin benct/lovelace-xiaomi-vacuum-card> Getting repository information
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] <Theme basnijholt/lovelace-ios-dark-mode-theme> Getting repository information
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] <Plugin bratanon/lovelace-conditional-entity-row> Getting repository information
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] <Plugin gadgetchnnel/lovelace-card-templater> Getting repository information
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] <Integration Concentricc/xiaomi_vacuum> Getting repository information
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] <Theme JuanMTech/google_dark_theme> Getting repository information
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] Did not update iantrich/config-template-card, content was not modified
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] Did not update hacs/integration, content was not modified
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] Did not update bruxy70/Garbage-Collection, content was not modified
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] Did not update bramkragten/weather-card, content was not modified
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] Did not update thomasloven/lovelace-slider-entity-row, content was not modified
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] Did not update amaximus/garbage-collection-card, content was not modified
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] Did not update JuanMTech/google_dark_theme, content was not modified
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] Did not update benct/lovelace-xiaomi-vacuum-card, content was not modified
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] Did not update Concentricc/xiaomi_vacuum, content was not modified
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] Did not update gadgetchnnel/lovelace-card-templater, content was not modified
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] Did not update maykar/lovelace-swipe-navigation, content was not modified
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] Did not update basnijholt/lovelace-ios-dark-mode-theme, content was not modified
2021-02-10 11:07:13 DEBUG (MainThread) [custom_components.hacs] Did not update kalkih/mini-graph-card, content was not modified
2021-02-10 11:07:14 WARNING (MainThread) [homeassistant.components.vacuum] Setup of vacuum platform xiaomi_vacuum is taking over 10 seconds.
2021-02-10 11:07:14 DEBUG (MainThread) [custom_components.hacs] Did not update bratanon/lovelace-conditional-entity-row, content was not modified
2021-02-10 11:07:14 DEBUG (MainThread) [custom_components.hacs] <Integration custom-components/remote_homeassistant> Running checks against 3.1
2021-02-10 11:07:14 ERROR (SyncWorker_3) [custom_components.xiaomi_vacuum.miio.miioprotocol] Unable to discover a device at address 10.128.191.195
2021-02-10 11:07:14 ERROR (SyncWorker_3) [custom_components.xiaomi_vacuum.miio.device] Unable to request properties [{'did': 'last_clean', 'siid': 18, 'piid': 13}, {'did': 'total_clean_count', 'siid': 18, 'piid': 14}, {'did': 'total_area', 'siid': 18, 'piid': 15}, {'did': 'total_log_start', 'siid': 18, 'piid': 16}, {'did': 'button_led', 'siid': 18, 'piid': 17}, {'did': 'clean_success', 'siid': 18, 'piid': 18}, {'did': 'life_sieve', 'siid': 19, 'piid': 1}, {'did': 'life_brush_side', 'siid': 19, 'piid': 2}, {'did': 'life_brush_main', 'siid': 19, 'piid': 3}, {'did': 'dnd_enabled', 'siid': 20, 'piid': 1}, {'did': 'dnd_start_time', 'siid': 20, 'piid': 2}, {'did': 'dnd_stop_time', 'siid': 20, 'piid': 3}, {'did': 'map_view', 'siid': 23, 'piid': 1}, {'did': 'audio_volume', 'siid': 24, 'piid': 1}]
2021-02-10 11:07:14 DEBUG (MainThread) [custom_components.hacs] <Integration custom-components/remote_homeassistant> All (0) checks passed
2021-02-10 11:07:14 INFO (MainThread) [custom_components.hacs] <Integration custom-components/remote_homeassistant> Registration completed
2021-02-10 11:07:19 ERROR (SyncWorker_3) [custom_components.xiaomi_vacuum.miio.miioprotocol] Unable to discover a device at address 10.128.191.195
2021-02-10 11:07:19 ERROR (SyncWorker_3) [custom_components.xiaomi_vacuum.miio.device] Unable to request properties [{'did': 'audio_language', 'siid': 24, 'piid': 3}, {'did': 'timezone', 'siid': 25, 'piid': 1}]
2021-02-10 11:07:19 ERROR (MainThread) [homeassistant.components.vacuum] xiaomi_vacuum: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 358, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
await task
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/xiaomi_vacuum/vacuum.py", line 322, in update
state = self._vacuum.status()
File "/config/custom_components/xiaomi_vacuum/miio/dreamevacuum.py", line 260, in status
return self.get_properties_for_dataclass(DreameStatus)
File "/config/custom_components/xiaomi_vacuum/miio/miot_device.py", line 63, in get_properties_for_dataclass
response = {
File "/config/custom_components/xiaomi_vacuum/miio/miot_device.py", line 64, in <dictcomp>
prop["did"]: prop["value"] if prop["code"] == 0 else None
TypeError: list indices must be integers or slices, not str
2021-02-10 11:07:19 DEBUG (MainThread) [queueman.manager] Queue execution finished for 15 tasks finished in 6.33 seconds
2021-02-10 11:07:19 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.critical'. Content did not change
2021-02-10 11:07:19 DEBUG (MainThread) [custom_components.hacs] Saving data
2021-02-10 11:07:19 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.hacs'. Content did not change
2021-02-10 11:07:19 DEBUG (MainThread) [queueman.manager] Checking out tasks to execute
2021-02-10 11:07:19 DEBUG (MainThread) [queueman.manager] Starting queue execution for 744 tasks
2021-02-10 11:07:20 DEBUG (MainThread) [queueman.manager] Queue execution finished for 744 tasks finished in 0.04 seconds
2021-02-10 11:07:20 DEBUG (MainThread) [custom_components.hacs] Recurring background task for installed repositories done
2021-02-10 11:07:20 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue
2021-02-10 11:07:20 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.RUNNING
2021-02-10 11:07:20 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 18.30s
2021-02-10 11:07:20 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2021-02-10 11:07:20 INFO (SyncWorker_8) [homeassistant.components.zeroconf] Starting Zeroconf broadcast
2021-02-10 11:07:20 INFO (MainThread) [homeassistant.core] Timer:starting
2021-02-10 11:07:20 INFO (MainThread) [homeassistant.components.automation.new_automation] Initialized trigger Notify Ionut that Laura is home
2021-02-10 11:07:20 INFO (MainThread) [homeassistant.components.automation.notify_laura_that_ionut_is_home] Initialized trigger Notify Laura that Ionut is Home
2021-02-10 11:07:20 INFO (MainThread) [homeassistant.components.automation.new_automation_2] Initialized trigger Shopping Memento Laura
2021-02-10 11:07:20 INFO (MainThread) [homeassistant.components.automation.leaving_home_laura] Initialized trigger Leaving home Laura
2021-02-10 11:07:20 INFO (MainThread) [homeassistant.components.automation.leaving_home_ionut] Initialized trigger Leaving home Ionut
2021-02-10 11:07:20 INFO (MainThread) [homeassistant.components.automation.new_automation_4] Initialized trigger test trash
2021-02-10 11:07:20 INFO (MainThread) [homeassistant.components.automation.shopping_memento_ionut] Initialized trigger Shopping memento Ionut
2021-02-10 11:07:20 INFO (MainThread) [homeassistant.components.automation.blueprint_mimi_test] Initialized trigger Mimi Schedule
2021-02-10 11:07:20 INFO (SyncWorker_1) [homeassistant.loader] Loaded xiaomi_aqara from homeassistant.components.xiaomi_aqara
2021-02-10 11:07:20 INFO (SyncWorker_5) [homeassistant.loader] Loaded xiaomi_miio from homeassistant.components.xiaomi_miio
2021-02-10 11:07:20 INFO (SyncWorker_0) [homeassistant.loader] Loaded discovery from homeassistant.components.discovery

**Comment by ionuttimofte53** [comment]
my issue dissappeared after removing my wifi range extenders. i'm suspecting the robot was using extended wifi ( cloned wifi, but still same ip ). cant be sure its that, but for the moment it is stable.
