### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by kamulchik** [Concentricc/xiaomi_vacuum#17]
Integration work is fine, but i have errors in log:
My settings:

```
vacuum:
- platform: xiaomi_vacuum
  host: 192.168.1.105
  token: "34id_of_vacuum1"
  name: Shnir
```
Log:
```

2021-02-22 20:03:52 ERROR (SyncWorker_5) [custom_components.xiaomi_vacuum.miio.miioprotocol] Unable to discover a device at address 192.168.1.105
2021-02-22 20:03:52 ERROR (SyncWorker_5) [custom_components.xiaomi_vacuum.miio.device] Unable to request properties [{'did': 'last_clean', 'siid': 18, 'piid': 13}, {'did': 'total_clean_count', 'siid': 18, 'piid': 14}, {'did': 'total_area', 'siid': 18, 'piid': 15}, {'did': 'total_log_start', 'siid': 18, 'piid': 16}, {'did': 'button_led', 'siid': 18, 'piid': 17}, {'did': 'clean_success', 'siid': 18, 'piid': 18}, {'did': 'life_sieve', 'siid': 19, 'piid': 1}, {'did': 'life_brush_side', 'siid': 19, 'piid': 2}, {'did': 'life_brush_main', 'siid': 19, 'piid': 3}, {'did': 'dnd_enabled', 'siid': 20, 'piid': 1}, {'did': 'dnd_start_time', 'siid': 20, 'piid': 2}, {'did': 'dnd_stop_time', 'siid': 20, 'piid': 3}, {'did': 'map_view', 'siid': 23, 'piid': 1}, {'did': 'audio_volume', 'siid': 24, 'piid': 1}]
2021-02-22 20:03:57 ERROR (SyncWorker_5) [custom_components.xiaomi_vacuum.miio.miioprotocol] Unable to discover a device at address 192.168.1.105
2021-02-22 20:03:57 ERROR (SyncWorker_5) [custom_components.xiaomi_vacuum.miio.device] Unable to request properties [{'did': 'audio_language', 'siid': 24, 'piid': 3}, {'did': 'timezone', 'siid': 25, 'piid': 1}]
2021-02-22 20:03:57 ERROR (MainThread) [homeassistant.helpers.entity] Update for vacuum.shnir fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 482, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_vacuum/vacuum.py", line 253, in update
    state = self._vacuum.status()
  File "/config/custom_components/xiaomi_vacuum/miio/dreamevacuum.py", line 259, in status
    return self.get_properties_for_dataclass(DreameStatus)
  File "/config/custom_components/xiaomi_vacuum/miio/miot_device.py", line 63, in get_properties_for_dataclass
    response = {
  File "/config/custom_components/xiaomi_vacuum/miio/miot_device.py", line 64, in <dictcomp>
    prop["did"]: prop["value"] if prop["code"] == 0 else None
TypeError: list indices must be integers or slices, not str
```
How i can fix it?

**Comment by DavidConnack** [comment]
These errors happen when there is a miscommunication between hass and the vacuum.
Usually if the vacuum has dropped the wifi signal.
It should work normally once the vacuum has reconnected.
