### ISSUE TITLE
zone cleaning error

### ISSUE THREAD

**Issue by igoralexeev** [Concentricc/xiaomi_vacuum#27]
`2021-06-17 09:20:45 INFO (MainThread) [homeassistant.components.script.clean_bathroom_room] Vacuum Bathroom room: Running script sequence
2021-06-17 09:20:45 INFO (MainThread) [homeassistant.components.script.clean_bathroom_room] Vacuum Bathroom room: Executing step call service
2021-06-17 09:20:45 ERROR (MainThread) [homeassistant.components.script.clean_bathroom_room] Vacuum Bathroom room: Error executing script. Unexpected error for call_service at pos 1: 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 368, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 568, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 760, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 252, in async_send_command
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 245, in send_command
    raise NotImplementedError()
NotImplementedError`

i use 

`sequence:
          - service: vacuum.send_command
            data_template:
              entity_id: vacuum.robot
              command: app_zoned_clean
              params: [[-4101,2816,-1483,4721,1]]`

**Comment by igoralexeev** [comment]
work fine with (pls add to manual)
`clean_kitchen:
        alias: "clean Kitchen"
        sequence:
          - service: xiaomi_vacuum.vacuum_clean_zone
            data_template:
              entity_id: vacuum.robot
              repeats: 1
              zone: '880,-900,5494,1290'`
